# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "common.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x63ommon.proto\x12\x10plosolver.common\x1a\x1fgoogle/protobuf/timestamp.proto"\xf3\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x11\n\tis_active\x18\x04 \x01(\x08\x12\x13\n\x0bis_verified\x18\x05 \x01(\x08\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1b\n\x13subscription_status\x18\x08 \x01(\t\x12\x19\n\x11\x63redits_remaining\x18\t \x01(\x05"\x8d\x01\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x35\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32$.plosolver.common.Error.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"X\n\x11PaginationRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08per_page\x18\x02 \x01(\x05\x12\x0f\n\x07sort_by\x18\x03 \x01(\t\x12\x12\n\nsort_order\x18\x04 \x01(\t"X\n\x12PaginationResponse\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08per_page\x18\x02 \x01(\x05\x12\r\n\x05total\x18\x03 \x01(\x05\x12\x13\n\x0btotal_pages\x18\x04 \x01(\x05\x42V\n\x19\x63om.plosolver.grpc.commonB\x0b\x43ommonProtoP\x01Z*github.com/plosolver/backend/protos/commonb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "common_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = (
        b"\n\031com.plosolver.grpc.commonB\013CommonProtoP\001Z*github.com/plosolver/backend/protos/common"
    )
    _globals["_ERROR_DETAILSENTRY"]._loaded_options = None
    _globals["_ERROR_DETAILSENTRY"]._serialized_options = b"8\001"
    _globals["_USER"]._serialized_start = 68
    _globals["_USER"]._serialized_end = 311
    _globals["_ERROR"]._serialized_start = 314
    _globals["_ERROR"]._serialized_end = 455
    _globals["_ERROR_DETAILSENTRY"]._serialized_start = 409
    _globals["_ERROR_DETAILSENTRY"]._serialized_end = 455
    _globals["_PAGINATIONREQUEST"]._serialized_start = 457
    _globals["_PAGINATIONREQUEST"]._serialized_end = 545
    _globals["_PAGINATIONRESPONSE"]._serialized_start = 547
    _globals["_PAGINATIONRESPONSE"]._serialized_end = 635
# @@protoc_insertion_point(module_scope)
