# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined routes_grpc."""
import warnings

import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from . import core_pb2 as core__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in core_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CoreServiceStub(object):
    """=============================================================================
    Core Service
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
            "/plosolver.core.CoreService/HealthCheck",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=core__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )
        self.GetSystemStatus = channel.unary_unary(
            "/plosolver.core.CoreService/GetSystemStatus",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=core__pb2.SystemStatusResponse.FromString,
            _registered_method=True,
        )
        self.GetUserStats = channel.unary_unary(
            "/plosolver.core.CoreService/GetUserStats",
            request_serializer=core__pb2.GetUserStatsRequest.SerializeToString,
            response_deserializer=core__pb2.GetUserStatsResponse.FromString,
            _registered_method=True,
        )


class CoreServiceServicer(object):
    """=============================================================================
    Core Service
    =============================================================================

    """

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSystemStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUserStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=core__pb2.HealthCheckResponse.SerializeToString,
        ),
        "GetSystemStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetSystemStatus,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=core__pb2.SystemStatusResponse.SerializeToString,
        ),
        "GetUserStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserStats,
            request_deserializer=core__pb2.GetUserStatsRequest.FromString,
            response_serializer=core__pb2.GetUserStatsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("plosolver.core.CoreService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("plosolver.core.CoreService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """=============================================================================
    Core Service
    =============================================================================

    """

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.core.CoreService/HealthCheck",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            core__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSystemStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.core.CoreService/GetSystemStatus",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            core__pb2.SystemStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUserStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.core.CoreService/GetUserStats",
            core__pb2.GetUserStatsRequest.SerializeToString,
            core__pb2.GetUserStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
