# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined routes_grpc."""
import warnings

import grpc

from . import hand_history_pb2 as hand__history__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in hand_history_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class HandHistoryServiceStub(object):
    """=============================================================================
    Hand History Service
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadHandHistory = channel.unary_unary(
            "/plosolver.hand_history.HandHistoryService/UploadHandHistory",
            request_serializer=hand__history__pb2.UploadHandHistoryRequest.SerializeToString,
            response_deserializer=hand__history__pb2.UploadHandHistoryResponse.FromString,
            _registered_method=True,
        )
        self.GetHandHistory = channel.unary_unary(
            "/plosolver.hand_history.HandHistoryService/GetHandHistory",
            request_serializer=hand__history__pb2.GetHandHistoryRequest.SerializeToString,
            response_deserializer=hand__history__pb2.GetHandHistoryResponse.FromString,
            _registered_method=True,
        )
        self.ListHandHistories = channel.unary_unary(
            "/plosolver.hand_history.HandHistoryService/ListHandHistories",
            request_serializer=hand__history__pb2.ListHandHistoriesRequest.SerializeToString,
            response_deserializer=hand__history__pb2.ListHandHistoriesResponse.FromString,
            _registered_method=True,
        )
        self.DeleteHandHistory = channel.unary_unary(
            "/plosolver.hand_history.HandHistoryService/DeleteHandHistory",
            request_serializer=hand__history__pb2.DeleteHandHistoryRequest.SerializeToString,
            response_deserializer=hand__history__pb2.DeleteHandHistoryResponse.FromString,
            _registered_method=True,
        )
        self.AnalyzeHandHistory = channel.unary_unary(
            "/plosolver.hand_history.HandHistoryService/AnalyzeHandHistory",
            request_serializer=hand__history__pb2.AnalyzeHandHistoryRequest.SerializeToString,
            response_deserializer=hand__history__pb2.AnalyzeHandHistoryResponse.FromString,
            _registered_method=True,
        )


class HandHistoryServiceServicer(object):
    """=============================================================================
    Hand History Service
    =============================================================================

    """

    def UploadHandHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetHandHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListHandHistories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteHandHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyzeHandHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_HandHistoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "UploadHandHistory": grpc.unary_unary_rpc_method_handler(
            servicer.UploadHandHistory,
            request_deserializer=hand__history__pb2.UploadHandHistoryRequest.FromString,
            response_serializer=hand__history__pb2.UploadHandHistoryResponse.SerializeToString,
        ),
        "GetHandHistory": grpc.unary_unary_rpc_method_handler(
            servicer.GetHandHistory,
            request_deserializer=hand__history__pb2.GetHandHistoryRequest.FromString,
            response_serializer=hand__history__pb2.GetHandHistoryResponse.SerializeToString,
        ),
        "ListHandHistories": grpc.unary_unary_rpc_method_handler(
            servicer.ListHandHistories,
            request_deserializer=hand__history__pb2.ListHandHistoriesRequest.FromString,
            response_serializer=hand__history__pb2.ListHandHistoriesResponse.SerializeToString,
        ),
        "DeleteHandHistory": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteHandHistory,
            request_deserializer=hand__history__pb2.DeleteHandHistoryRequest.FromString,
            response_serializer=hand__history__pb2.DeleteHandHistoryResponse.SerializeToString,
        ),
        "AnalyzeHandHistory": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeHandHistory,
            request_deserializer=hand__history__pb2.AnalyzeHandHistoryRequest.FromString,
            response_serializer=hand__history__pb2.AnalyzeHandHistoryResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "plosolver.hand_history.HandHistoryService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("plosolver.hand_history.HandHistoryService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class HandHistoryService(object):
    """=============================================================================
    Hand History Service
    =============================================================================

    """

    @staticmethod
    def UploadHandHistory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.hand_history.HandHistoryService/UploadHandHistory",
            hand__history__pb2.UploadHandHistoryRequest.SerializeToString,
            hand__history__pb2.UploadHandHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetHandHistory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.hand_history.HandHistoryService/GetHandHistory",
            hand__history__pb2.GetHandHistoryRequest.SerializeToString,
            hand__history__pb2.GetHandHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListHandHistories(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.hand_history.HandHistoryService/ListHandHistories",
            hand__history__pb2.ListHandHistoriesRequest.SerializeToString,
            hand__history__pb2.ListHandHistoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteHandHistory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.hand_history.HandHistoryService/DeleteHandHistory",
            hand__history__pb2.DeleteHandHistoryRequest.SerializeToString,
            hand__history__pb2.DeleteHandHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AnalyzeHandHistory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.hand_history.HandHistoryService/AnalyzeHandHistory",
            hand__history__pb2.AnalyzeHandHistoryRequest.SerializeToString,
            hand__history__pb2.AnalyzeHandHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
