# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined routes_grpc."""
import warnings

import grpc

from . import subscription_pb2 as subscription__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in subscription_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SubscriptionServiceStub(object):
    """=============================================================================
    Subscription Service
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSubscription = channel.unary_unary(
            "/plosolver.subscription.SubscriptionService/GetSubscription",
            request_serializer=subscription__pb2.GetSubscriptionRequest.SerializeToString,
            response_deserializer=subscription__pb2.GetSubscriptionResponse.FromString,
            _registered_method=True,
        )
        self.CreateSubscription = channel.unary_unary(
            "/plosolver.subscription.SubscriptionService/CreateSubscription",
            request_serializer=subscription__pb2.CreateSubscriptionRequest.SerializeToString,
            response_deserializer=subscription__pb2.CreateSubscriptionResponse.FromString,
            _registered_method=True,
        )
        self.UpdateSubscription = channel.unary_unary(
            "/plosolver.subscription.SubscriptionService/UpdateSubscription",
            request_serializer=subscription__pb2.UpdateSubscriptionRequest.SerializeToString,
            response_deserializer=subscription__pb2.UpdateSubscriptionResponse.FromString,
            _registered_method=True,
        )
        self.CancelSubscription = channel.unary_unary(
            "/plosolver.subscription.SubscriptionService/CancelSubscription",
            request_serializer=subscription__pb2.CancelSubscriptionRequest.SerializeToString,
            response_deserializer=subscription__pb2.CancelSubscriptionResponse.FromString,
            _registered_method=True,
        )
        self.GetUsage = channel.unary_unary(
            "/plosolver.subscription.SubscriptionService/GetUsage",
            request_serializer=subscription__pb2.GetUsageRequest.SerializeToString,
            response_deserializer=subscription__pb2.GetUsageResponse.FromString,
            _registered_method=True,
        )
        self.GetBillingHistory = channel.unary_unary(
            "/plosolver.subscription.SubscriptionService/GetBillingHistory",
            request_serializer=subscription__pb2.GetBillingHistoryRequest.SerializeToString,
            response_deserializer=subscription__pb2.GetBillingHistoryResponse.FromString,
            _registered_method=True,
        )


class SubscriptionServiceServicer(object):
    """=============================================================================
    Subscription Service
    =============================================================================

    """

    def GetSubscription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateSubscription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateSubscription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelSubscription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetBillingHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SubscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetSubscription": grpc.unary_unary_rpc_method_handler(
            servicer.GetSubscription,
            request_deserializer=subscription__pb2.GetSubscriptionRequest.FromString,
            response_serializer=subscription__pb2.GetSubscriptionResponse.SerializeToString,
        ),
        "CreateSubscription": grpc.unary_unary_rpc_method_handler(
            servicer.CreateSubscription,
            request_deserializer=subscription__pb2.CreateSubscriptionRequest.FromString,
            response_serializer=subscription__pb2.CreateSubscriptionResponse.SerializeToString,
        ),
        "UpdateSubscription": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateSubscription,
            request_deserializer=subscription__pb2.UpdateSubscriptionRequest.FromString,
            response_serializer=subscription__pb2.UpdateSubscriptionResponse.SerializeToString,
        ),
        "CancelSubscription": grpc.unary_unary_rpc_method_handler(
            servicer.CancelSubscription,
            request_deserializer=subscription__pb2.CancelSubscriptionRequest.FromString,
            response_serializer=subscription__pb2.CancelSubscriptionResponse.SerializeToString,
        ),
        "GetUsage": grpc.unary_unary_rpc_method_handler(
            servicer.GetUsage,
            request_deserializer=subscription__pb2.GetUsageRequest.FromString,
            response_serializer=subscription__pb2.GetUsageResponse.SerializeToString,
        ),
        "GetBillingHistory": grpc.unary_unary_rpc_method_handler(
            servicer.GetBillingHistory,
            request_deserializer=subscription__pb2.GetBillingHistoryRequest.FromString,
            response_serializer=subscription__pb2.GetBillingHistoryResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "plosolver.subscription.SubscriptionService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("plosolver.subscription.SubscriptionService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SubscriptionService(object):
    """=============================================================================
    Subscription Service
    =============================================================================

    """

    @staticmethod
    def GetSubscription(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.subscription.SubscriptionService/GetSubscription",
            subscription__pb2.GetSubscriptionRequest.SerializeToString,
            subscription__pb2.GetSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateSubscription(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.subscription.SubscriptionService/CreateSubscription",
            subscription__pb2.CreateSubscriptionRequest.SerializeToString,
            subscription__pb2.CreateSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateSubscription(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.subscription.SubscriptionService/UpdateSubscription",
            subscription__pb2.UpdateSubscriptionRequest.SerializeToString,
            subscription__pb2.UpdateSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelSubscription(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.subscription.SubscriptionService/CancelSubscription",
            subscription__pb2.CancelSubscriptionRequest.SerializeToString,
            subscription__pb2.CancelSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUsage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.subscription.SubscriptionService/GetUsage",
            subscription__pb2.GetUsageRequest.SerializeToString,
            subscription__pb2.GetUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetBillingHistory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.subscription.SubscriptionService/GetBillingHistory",
            subscription__pb2.GetBillingHistoryRequest.SerializeToString,
            subscription__pb2.GetBillingHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
