# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "core.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

from . import common_pb2 as common__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ncore.proto\x12\x0eplosolver.core\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x63ommon.proto"e\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"\xb9\x02\n\x14SystemStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x44\n\x08services\x18\x02 \x03(\x0b\x32\x32.plosolver.core.SystemStatusResponse.ServicesEntry\x12\x42\n\x07metrics\x18\x03 \x03(\x0b\x32\x31.plosolver.core.SystemStatusResponse.MetricsEntry\x12&\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x17.plosolver.common.Error\x1a/\n\rServicesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01"&\n\x13GetUserStatsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t"h\n\x14GetUserStatsResponse\x12(\n\x05stats\x18\x01 \x01(\x0b\x32\x19.plosolver.core.UserStats\x12&\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x17.plosolver.common.Error"\xe7\x01\n\tUserStats\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x16\n\x0etotal_analyses\x18\x02 \x01(\x05\x12\x1b\n\x13\x61nalyses_this_month\x18\x03 \x01(\x05\x12\x14\n\x0c\x63redits_used\x18\x04 \x01(\x05\x12\x19\n\x11\x63redits_remaining\x18\x05 \x01(\x05\x12\x31\n\rlast_analysis\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0cmember_since\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x85\x02\n\x0b\x43oreService\x12J\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a#.plosolver.core.HealthCheckResponse\x12O\n\x0fGetSystemStatus\x12\x16.google.protobuf.Empty\x1a$.plosolver.core.SystemStatusResponse\x12Y\n\x0cGetUserStats\x12#.plosolver.core.GetUserStatsRequest\x1a$.plosolver.core.GetUserStatsResponseBP\n\x17\x63om.plosolver.grpc.coreB\tCoreProtoP\x01Z(github.com/plosolver/backend/protos/coreb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "core_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\027com.plosolver.grpc.coreB\tCoreProtoP\001Z(github.com/plosolver/backend/protos/core"
    _globals["_SYSTEMSTATUSRESPONSE_SERVICESENTRY"]._loaded_options = None
    _globals["_SYSTEMSTATUSRESPONSE_SERVICESENTRY"]._serialized_options = b"8\001"
    _globals["_SYSTEMSTATUSRESPONSE_METRICSENTRY"]._loaded_options = None
    _globals["_SYSTEMSTATUSRESPONSE_METRICSENTRY"]._serialized_options = b"8\001"
    _globals["_HEALTHCHECKRESPONSE"]._serialized_start = 106
    _globals["_HEALTHCHECKRESPONSE"]._serialized_end = 207
    _globals["_SYSTEMSTATUSRESPONSE"]._serialized_start = 210
    _globals["_SYSTEMSTATUSRESPONSE"]._serialized_end = 523
    _globals["_SYSTEMSTATUSRESPONSE_SERVICESENTRY"]._serialized_start = 428
    _globals["_SYSTEMSTATUSRESPONSE_SERVICESENTRY"]._serialized_end = 475
    _globals["_SYSTEMSTATUSRESPONSE_METRICSENTRY"]._serialized_start = 477
    _globals["_SYSTEMSTATUSRESPONSE_METRICSENTRY"]._serialized_end = 523
    _globals["_GETUSERSTATSREQUEST"]._serialized_start = 525
    _globals["_GETUSERSTATSREQUEST"]._serialized_end = 563
    _globals["_GETUSERSTATSRESPONSE"]._serialized_start = 565
    _globals["_GETUSERSTATSRESPONSE"]._serialized_end = 669
    _globals["_USERSTATS"]._serialized_start = 672
    _globals["_USERSTATS"]._serialized_end = 903
    _globals["_CORESERVICE"]._serialized_start = 906
    _globals["_CORESERVICE"]._serialized_end = 1167
# @@protoc_insertion_point(module_scope)
