# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from . import job_pb2 as job__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in job_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class JobServiceStub(object):
    """=============================================================================
    Job Service
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateJob = channel.unary_unary(
            "/plosolver.job.JobService/CreateJob",
            request_serializer=job__pb2.CreateJobRequest.SerializeToString,
            response_deserializer=job__pb2.CreateJobResponse.FromString,
            _registered_method=True,
        )
        self.GetJob = channel.unary_unary(
            "/plosolver.job.JobService/GetJob",
            request_serializer=job__pb2.GetJobRequest.SerializeToString,
            response_deserializer=job__pb2.GetJobResponse.FromString,
            _registered_method=True,
        )
        self.ListJobs = channel.unary_unary(
            "/plosolver.job.JobService/ListJobs",
            request_serializer=job__pb2.ListJobsRequest.SerializeToString,
            response_deserializer=job__pb2.ListJobsResponse.FromString,
            _registered_method=True,
        )
        self.UpdateJob = channel.unary_unary(
            "/plosolver.job.JobService/UpdateJob",
            request_serializer=job__pb2.UpdateJobRequest.SerializeToString,
            response_deserializer=job__pb2.UpdateJobResponse.FromString,
            _registered_method=True,
        )
        self.DeleteJob = channel.unary_unary(
            "/plosolver.job.JobService/DeleteJob",
            request_serializer=job__pb2.DeleteJobRequest.SerializeToString,
            response_deserializer=job__pb2.DeleteJobResponse.FromString,
            _registered_method=True,
        )
        self.CancelJob = channel.unary_unary(
            "/plosolver.job.JobService/CancelJob",
            request_serializer=job__pb2.CancelJobRequest.SerializeToString,
            response_deserializer=job__pb2.CancelJobResponse.FromString,
            _registered_method=True,
        )


class JobServiceServicer(object):
    """=============================================================================
    Job Service
    =============================================================================

    """

    def CreateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateJob": grpc.unary_unary_rpc_method_handler(
            servicer.CreateJob,
            request_deserializer=job__pb2.CreateJobRequest.FromString,
            response_serializer=job__pb2.CreateJobResponse.SerializeToString,
        ),
        "GetJob": grpc.unary_unary_rpc_method_handler(
            servicer.GetJob,
            request_deserializer=job__pb2.GetJobRequest.FromString,
            response_serializer=job__pb2.GetJobResponse.SerializeToString,
        ),
        "ListJobs": grpc.unary_unary_rpc_method_handler(
            servicer.ListJobs,
            request_deserializer=job__pb2.ListJobsRequest.FromString,
            response_serializer=job__pb2.ListJobsResponse.SerializeToString,
        ),
        "UpdateJob": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateJob,
            request_deserializer=job__pb2.UpdateJobRequest.FromString,
            response_serializer=job__pb2.UpdateJobResponse.SerializeToString,
        ),
        "DeleteJob": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteJob,
            request_deserializer=job__pb2.DeleteJobRequest.FromString,
            response_serializer=job__pb2.DeleteJobResponse.SerializeToString,
        ),
        "CancelJob": grpc.unary_unary_rpc_method_handler(
            servicer.CancelJob,
            request_deserializer=job__pb2.CancelJobRequest.FromString,
            response_serializer=job__pb2.CancelJobResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("plosolver.job.JobService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("plosolver.job.JobService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class JobService(object):
    """=============================================================================
    Job Service
    =============================================================================

    """

    @staticmethod
    def CreateJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.job.JobService/CreateJob",
            job__pb2.CreateJobRequest.SerializeToString,
            job__pb2.CreateJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.job.JobService/GetJob",
            job__pb2.GetJobRequest.SerializeToString,
            job__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListJobs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.job.JobService/ListJobs",
            job__pb2.ListJobsRequest.SerializeToString,
            job__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.job.JobService/UpdateJob",
            job__pb2.UpdateJobRequest.SerializeToString,
            job__pb2.UpdateJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.job.JobService/DeleteJob",
            job__pb2.DeleteJobRequest.SerializeToString,
            job__pb2.DeleteJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.job.JobService/CancelJob",
            job__pb2.CancelJobRequest.SerializeToString,
            job__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
