# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from . import solver_pb2 as solver__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in solver_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SolverServiceStub(object):
    """=============================================================================
    Solver Service
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSolverConfig = channel.unary_unary(
            "/plosolver.solver.SolverService/GetSolverConfig",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=solver__pb2.SolverConfigResponse.FromString,
            _registered_method=True,
        )
        self.GetHandBuckets = channel.unary_unary(
            "/plosolver.solver.SolverService/GetHandBuckets",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=solver__pb2.HandBucketsResponse.FromString,
            _registered_method=True,
        )
        self.GetPlayerProfiles = channel.unary_unary(
            "/plosolver.solver.SolverService/GetPlayerProfiles",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=solver__pb2.PlayerProfilesResponse.FromString,
            _registered_method=True,
        )
        self.AnalyzeSpot = channel.unary_unary(
            "/plosolver.solver.SolverService/AnalyzeSpot",
            request_serializer=solver__pb2.AnalyzeSpotRequest.SerializeToString,
            response_deserializer=solver__pb2.AnalyzeSpotResponse.FromString,
            _registered_method=True,
        )
        self.GetAnalysisStatus = channel.unary_unary(
            "/plosolver.solver.SolverService/GetAnalysisStatus",
            request_serializer=solver__pb2.GetAnalysisStatusRequest.SerializeToString,
            response_deserializer=solver__pb2.GetAnalysisStatusResponse.FromString,
            _registered_method=True,
        )
        self.CancelAnalysis = channel.unary_unary(
            "/plosolver.solver.SolverService/CancelAnalysis",
            request_serializer=solver__pb2.CancelAnalysisRequest.SerializeToString,
            response_deserializer=solver__pb2.CancelAnalysisResponse.FromString,
            _registered_method=True,
        )


class SolverServiceServicer(object):
    """=============================================================================
    Solver Service
    =============================================================================

    """

    def GetSolverConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetHandBuckets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPlayerProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyzeSpot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAnalysisStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SolverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetSolverConfig": grpc.unary_unary_rpc_method_handler(
            servicer.GetSolverConfig,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=solver__pb2.SolverConfigResponse.SerializeToString,
        ),
        "GetHandBuckets": grpc.unary_unary_rpc_method_handler(
            servicer.GetHandBuckets,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=solver__pb2.HandBucketsResponse.SerializeToString,
        ),
        "GetPlayerProfiles": grpc.unary_unary_rpc_method_handler(
            servicer.GetPlayerProfiles,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=solver__pb2.PlayerProfilesResponse.SerializeToString,
        ),
        "AnalyzeSpot": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeSpot,
            request_deserializer=solver__pb2.AnalyzeSpotRequest.FromString,
            response_serializer=solver__pb2.AnalyzeSpotResponse.SerializeToString,
        ),
        "GetAnalysisStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetAnalysisStatus,
            request_deserializer=solver__pb2.GetAnalysisStatusRequest.FromString,
            response_serializer=solver__pb2.GetAnalysisStatusResponse.SerializeToString,
        ),
        "CancelAnalysis": grpc.unary_unary_rpc_method_handler(
            servicer.CancelAnalysis,
            request_deserializer=solver__pb2.CancelAnalysisRequest.FromString,
            response_serializer=solver__pb2.CancelAnalysisResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("plosolver.solver.SolverService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("plosolver.solver.SolverService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SolverService(object):
    """=============================================================================
    Solver Service
    =============================================================================

    """

    @staticmethod
    def GetSolverConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.solver.SolverService/GetSolverConfig",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            solver__pb2.SolverConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetHandBuckets(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.solver.SolverService/GetHandBuckets",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            solver__pb2.HandBucketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPlayerProfiles(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.solver.SolverService/GetPlayerProfiles",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            solver__pb2.PlayerProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AnalyzeSpot(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.solver.SolverService/AnalyzeSpot",
            solver__pb2.AnalyzeSpotRequest.SerializeToString,
            solver__pb2.AnalyzeSpotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetAnalysisStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.solver.SolverService/GetAnalysisStatus",
            solver__pb2.GetAnalysisStatusRequest.SerializeToString,
            solver__pb2.GetAnalysisStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelAnalysis(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/plosolver.solver.SolverService/CancelAnalysis",
            solver__pb2.CancelAnalysisRequest.SerializeToString,
            solver__pb2.CancelAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
